### ISSUE TITLE
Internal server error on Heroku

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#54]
App runs fine both on my laptop (linux) and desktop (osx). But I'm not sure what is the problem. Heres logs from `heroku logs`

```bash
2015-11-17T19:43:58.695699+00:00 app[web.1]: 2015-11-17 19:43:58 - NoMethodError - undefined method `name' for nil:NilClass:
2015-11-17T19:43:58.695703+00:00 app[web.1]: 	/app/views/timeline.erb:51:in `block (2 levels) in singleton class'
2015-11-17T19:43:58.695704+00:00 app[web.1]: 	/app/views/timeline.erb:50:in `each'
2015-11-17T19:43:58.695705+00:00 app[web.1]: 	/app/views/timeline.erb:50:in `block in singleton class'
2015-11-17T19:43:58.695706+00:00 app[web.1]: 	/app/views/timeline.erb:-6:in `instance_eval'
2015-11-17T19:43:58.695706+00:00 app[web.1]: 	/app/views/timeline.erb:-6:in `singleton class'
2015-11-17T19:43:58.695707+00:00 app[web.1]: 	/app/views/timeline.erb:-8:in `__tilt_69828649883580'
2015-11-17T19:43:58.695708+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
2015-11-17T19:43:58.695710+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
2015-11-17T19:43:58.695709+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
2015-11-17T19:43:58.695710+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:822:in `render'
2015-11-17T19:43:58.695711+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:666:in `erb'
2015-11-17T19:43:58.695712+00:00 app[web.1]: 	/app/app.rb:81:in `block in <top (required)>'
2015-11-17T19:43:58.695712+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
2015-11-17T19:43:58.695713+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'

... (several more lines of trace stack not seemingly relevent)

2015-11-17T19:43:58.695746+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
2015-11-17T19:43:58.696337+00:00 app[web.1]: 129.64.55.161 - - [17/Nov/2015:19:43:58 +0000] "GET /timeline HTTP/1.1" 500 30 0.0117
2015-11-17T19:43:58.695749+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/configuration.rb:79:in `call'
2015-11-17T19:43:58.690381+00:00 app[web.1]: WARN: tilt autoloading 'tilt/erubis' in a non thread-safe way; explicit require 'tilt/erubis' suggested.
2015-11-17T19:43:59.198822+00:00 heroku[router]: at=info method=GET path="/" host=afternoon-peak-6349.herokuapp.com request_id=68034063-61c7-41cc-8e84-2305bfb184f7 fwd="129.64.55.161" dyno=web.1 connect=5ms service=4ms status=302 bytes=768
2015-11-17T19:43:59.198630+00:00 app[web.1]: 129.64.55.161 - - [17/Nov/2015:19:43:59 +0000] "GET / HTTP/1.1" 302 - 0.0020

```

##### app.rb

```ruby
 75 get '/timeline' do
 76   if session[:logged_in_user_name].nil?
 77     @tweets = Tweet.all.order(tweeted_at: :desc).take(50)                                                                                                                     
 78   else
 79     @tweets = User.find(session[:logged_in_user_id]).feeds.order(tweeted_at: :desc)                                                                                           
 80   end
 81   erb :timeline                                                                                                                                                               
 82 end     
```

##### timelime.erb
```ruby
 48         <h3> Timeline</h3>
 49         <ul>
 50             <% @tweets.each do |t|%>
 51             <% op = t.user.name %>
 52             <li><%=
 53                 "<a href=\"/profile/#{op}\"> #{op} </a> : #{t.content}"
 54             %></li>
```
Judging from the error trace, when line 81 calls `timeline.erb`, `@tweet` is filled with `nil` or something. Maybe database issue?

**Comment by keighrim** [comment]
I mean, postgres issue?

**Comment by shuchenku** [comment]
We have some lingering tweets from deleted users. I removed those and the bug is gone now.
